apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttpbin-deploy
  labels:
    app: myhttpbin
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myhttpbin
  template:
     metadata:
       labels:
         app: httpbin
     spec:
       containers:
       - name: httpbin-container
         image:  smrutipriya/httpbin:app
         ports:
         - containerPort: 80