apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deploy
  labels:
    app: httpbin
spec:
  replicas: 3
  selector:
      matchLabels:
         app: httpbin
  template:
     metadata:
       labels:
         app: httpbin
     spec:
       containers:
       - name: httpbin-container
         image:  smrutipriya/httpbin
         ports:
         - containerPort: 80