apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
   replicas: 2
   selector: 
     app: nginx
     version: 2.6.2
     
   template:
     metadata:
       labels:
          app: nginx
          version: 2.6.2
          
     spec:
        containers:
        - name: httpbin-container   
          image: nginx
          ports:
          - containerPort: 8080 