apiVersion: v1
kind: ReplicationController
metadata:
  name: httpbin-rc
spec:
   replicas: 2
   selector: 
     app: httpbin
     version: 2.6.2
     
   template:
     metadata:
       labels:
          app: httpbin
          version: 2.6.2
          
     spec:
        containers:
        - name: httpbin-container   
          image: smrutipriya/httpbin
          ports:
          - containerPort: 8080 